# Generated by Django 5.2.6 on 2025-09-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="age",
            field=models.PositiveIntegerField(),
        ),
    ]
