# Generated by Django 5.2.6 on 2025-09-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_customer_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
